version: "3.9"
services:
  mlflow:
    container_name: cv-inside-tracker
    image: cv-inside-tracker
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - public
      - internal
    entrypoint: mlflow server -h 0.0.0.0
networks:
  internal:
  public:
    driver: bridge